const base = "/assets";

const assetMap = {
  bug: `${base}/bug.png`,
  dark: `${base}/dark.png`,
  dragon: `${base}/dragon.png`,
  electric: `${base}/electric.png`,
  fairy: `${base}/fairy.png`,
  fighting: `${base}/fighting.png`,
  fire: `${base}/fire.png`,
  flying: `${base}/flying.png`,
  ghost: `${base}/ghost.png`,
  grass: `${base}/grass.png`,
  ground: `${base}/ground.png`,
  ice: `${base}/ice.png`,
  normal: `${base}/normal.png`,
  poison: `${base}/poison.png`,
  psychic: `${base}/psychic.png`,
  rock: `${base}/rock.png`,
  steel: `${base}/steel.png`,
  water: `${base}/water.png`,

  "filter-bug": `${base}/filter-bug.svg`,
  "filter-dark": `${base}/filter-dark.svg`,
  "filter-dragon": `${base}/filter-dragon.svg`,
  "filter-electric": `${base}/filter-electric.svg`,
  "filter-fairy": `${base}/filter-fairy.svg`,
  "filter-fighting": `${base}/filter-fighting.svg`,
  "filter-fire": `${base}/filter-fire.svg`,
  "filter-flying": `${base}/filter-flying.svg`,
  "filter-ghost": `${base}/filter-ghost.svg`,
  "filter-grass": `${base}/filter-grass.svg`,
  "filter-ground": `${base}/filter-ground.svg`,
  "filter-ice": `${base}/filter-ice.svg`,
  "filter-normal": `${base}/filter-normal.svg`,
  "filter-poison": `${base}/filter-poison.svg`,
  "filter-psychic": `${base}/filter-psychic.svg`,
  "filter-rock": `${base}/filter-rock.svg`,
  "filter-steel": `${base}/filter-steel.svg`,
  "filter-water": `${base}/filter-water.svg`,

  mega: `${base}/mega.png`,
  "other-forms": `${base}/other-forms.png`,
  "other-forms.jpg": `${base}/other-forms.jpg`,
  "pokemon-filter": `${base}/pokemon-filter.png`,
  "pokedex-icon": `${base}/pokedex-icon.png`,
  "pokeball-bg": `${base}/pokeball-bg.png`,
  "pokeball-bg.jpg": `${base}/pokeball-bg.jpg`,
  "pokeball-large": `${base}/pokeball-large.png`,
  "pokeball-small": `${base}/pokeball-small.png`,
  "human_comp": `${base}/human_comp.png`,
  "human_comp.png": `${base}/human_comp.png`,
  "silhouette_default": `${base}/silhouette_default.png`,
  "silhouette_default.png": `${base}/silhouette_default.png`,
  "placeholder-200": `${base}/silhouette_default.png`,
  "placeholder-64": `${base}/silhouette_default.png`,
};

export default assetMap;
